Este escenario se basa en una empresa ficticia:

Botium Toys es una pequeña empresa estadounidense que desarrolla y vende juguetes. La empresa tiene una única ubicación física, que sirve como oficina principal, escaparate y almacén para sus productos. Sin embargo, la presencia en línea de Botium Toy ha crecido, atrayendo a clientes en los EE.UU. y en el extranjero. Como resultado, su departamento de tecnología de la información (TI) está bajo una presión cada vez mayor para apoyar su mercado en línea en todo el mundo.

La directora del departamento de TI ha decidido que es necesario realizar una auditoría interna de TI. Le preocupa mantener el cumplimiento y las operaciones comerciales a medida que la empresa crece sin un plan claro. Ella cree que una auditoría interna puede ayudar a proteger mejor la infraestructura de la empresa y ayudarles a identificar y mitigar los posibles riesgos, amenazas o vulnerabilidades de los activos críticos. El directivo también está interesado en asegurarse de que cumplen la normativa relacionada con el procesamiento interno y la aceptación de pagos en línea y la realización de negocios en la Unión Europea (UE).

El responsable de TI comienza aplicando el Marco de Ciberseguridad del Instituto Nacional de Estándares y Tecnología (NIST CSF), estableciendo un ámbito y unos objetivos de auditoría, enumerando los activos gestionados actualmente por el departamento de TI y completando una evaluación de riesgos. El objetivo de la auditoría es proporcionar una visión general de los riesgos y/o multas que la empresa podría experimentar debido al estado actual de su postura de seguridad.

Su tarea consiste en revisar el alcance, los objetivos y el informe de evaluación de riesgos del responsable de TI. A continuación, realice una auditoría interna completando una lista de comprobación de controles y cumplimiento.
